import {describe,it,expect,vi} from 'vitest';
import {createHmac} from 'node:crypto';
import {handleNativeAriShadow,type NativeAriBatch} from '../lib/native-ari-shadow-receiver';
const now=Date.parse('2026-09-30T12:00:00Z'),secret='shadow-receiver-fixture-secret-long-enough',connection='sandbox_route';
const config={mode:'validate_only',signingSecrets:JSON.stringify({[connection]:secret})};
function batch():NativeAriBatch{return {contractVersion:1,eventId:'shadow_event',propertyId:'pms_property',connector:'iratepilot',connectionId:connection,sourceVersion:1,generatedAt:new Date(now).toISOString(),updates:[{date:'2026-10-01',roomTypeId:'room',ratePlanId:'BAR',rateMinor:10000,available:0,currency:'USD',minimumStay:1,maximumStay:null,restrictions:[]}]}}
function request(raw=JSON.stringify(batch()),timestamp=String(now/1000),headers:Record<string,string>={}){return new Request('https://www.iratepilot.com/api/pms/ari',{method:'POST',headers:{'content-type':'application/json','x-irp-connection':connection,'x-irp-timestamp':timestamp,'x-irp-signature':createHmac('sha256',secret).update(`${timestamp}.${connection}.${raw}`).digest('hex'),...headers},body:raw})}
const validate=()=>vi.fn(async()=>({outcome:'validated' as const,persisted:false as const,certified:false as const,observations:[{targetMatches:true}]}));
describe('native ARI read-only receiver',()=>{
 it('stays disabled unless validate_only is selected',async()=>{const read=validate();expect((await handleNativeAriShadow(request(),{},read,now)).status).toBe(503);expect(read).not.toHaveBeenCalled()});
 it('authenticates exact raw bytes and returns validation without applied delivery',async()=>{const read=validate(),response=await handleNativeAriShadow(request(),config,read,now),body=await response.json();expect(response.status).toBe(200);expect(body).toMatchObject({outcome:'validated',persisted:false,certified:false,eventId:'shadow_event',sourceVersion:1});expect(body.outcome).not.toBe('applied');expect(response.headers.get('cache-control')).toBe('no-store');expect(read).toHaveBeenCalledWith(batch())});
 it('rejects a changed signature and an expired timestamp before reading the database',async()=>{const read=validate();expect((await handleNativeAriShadow(request(undefined,undefined,{'x-irp-signature':'0'.repeat(64)}),config,read,now)).status).toBe(401);expect((await handleNativeAriShadow(request(undefined,String(now/1000-301)),config,read,now)).status).toBe(401);expect(read).not.toHaveBeenCalled()});
 it('rejects mismatched connection identity even with a valid signature',async()=>{const b=batch();b.connectionId='another_route';const read=validate();expect((await handleNativeAriShadow(request(JSON.stringify(b)),config,read,now)).status).toBe(422);expect(read).not.toHaveBeenCalled()});
 it('rejects duplicate updates, stay restrictions, tax extensions and fractional cents',async()=>{for(const change of [(b:NativeAriBatch)=>b.updates.push({...b.updates[0]}),(b:NativeAriBatch)=>Object.assign(b.updates[0],{minimumStay:2}),(b:NativeAriBatch)=>Object.assign(b.updates[0],{taxMinor:500}),(b:NativeAriBatch)=>b.updates[0].rateMinor=10000.5]){const b=batch();change(b);const read=validate();expect((await handleNativeAriShadow(request(JSON.stringify(b)),config,read,now)).status).toBe(422);expect(read).not.toHaveBeenCalled()}});
 it('bounds streamed bytes even when content-length is understated',async()=>{const read=validate();expect((await handleNativeAriShadow(request('x'.repeat(262145),undefined,{'content-length':'1'}),config,read,now)).status).toBe(413);expect(read).not.toHaveBeenCalled()});
 it('rejects invalid JSON and invalid calendar dates',async()=>{const read=validate();expect((await handleNativeAriShadow(request('{'),config,read,now)).status).toBe(400);const b=batch();b.updates[0].date='2026-02-30';expect((await handleNativeAriShadow(request(JSON.stringify(b)),config,read,now)).status).toBe(422);expect(read).not.toHaveBeenCalled()});
 it('does not expose database errors or accept a write-success receipt',async()=>{const read=vi.fn(async()=>{throw Error(secret)});const result=await handleNativeAriShadow(request(),config,read,now);expect(result.status).toBe(503);expect(JSON.stringify(await result.json())).not.toContain(secret);const forged=vi.fn(async()=>({outcome:'applied',persisted:true,certified:true,observations:[{}]}));expect((await handleNativeAriShadow(request(),config,forged as unknown as ReturnType<typeof validate>,now)).status).toBe(503)});
});
