"use client";
import { useEffect,useState } from "react";
type Trip={id:string;confirmation_code:string;check_in:string;check_out:string;guests:number;fees:number;total:number;status:string;cancellation_reason?:string|null;properties?:{name?:string}|null;rooms?:{name?:string}|null};
export function CustomerTrips(){
  const [trips,setTrips]=useState<Trip[]>([]);const [message,setMessage]=useState("Loading trips…");
  useEffect(()=>{fetch("/api/bookings").then(async(response)=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setTrips(body.data);setMessage("");}).catch((error:Error)=>setMessage(error.message));},[]);
  async function cancel(id:string){if(!window.confirm("Cancel this pending booking request?"))return;const response=await fetch(`/api/bookings/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:"Cancelled by traveler"})});const body=await response.json();setMessage(response.ok?body.message:body.error);if(response.ok)setTrips((current)=>current.map((trip)=>trip.id===id?{...trip,status:"cancelled",cancellation_reason:"Cancelled by traveler"}:trip));}
  return <section className="card mt-8 overflow-hidden">{message&&<p role="status" className="p-6 text-sm text-slate-500">{message}</p>}<div className="divide-y">{trips.map((trip)=><article key={trip.id} className="grid gap-4 p-6 lg:grid-cols-[1fr_auto_auto] lg:items-center"><div><strong>{trip.properties?.name||"Property"}</strong><p className="mt-1 text-sm text-slate-500">{trip.rooms?.name} · {trip.check_in} to {trip.check_out} · {trip.guests} guests</p><p className="mt-2 text-xs uppercase tracking-wider text-slate-500">{trip.confirmation_code} · {trip.status}</p>{trip.cancellation_reason&&<p className="mt-2 text-sm text-red-700">{trip.cancellation_reason}</p>}</div><div className="lg:text-right"><strong>${Number(trip.total).toFixed(2)}</strong><p className="text-xs text-slate-500">Includes ${Number(trip.fees).toFixed(2)} service fee</p></div>{trip.status==="pending"&&<button onClick={()=>cancel(trip.id)} className="btn-secondary">Cancel request</button>}</article>)}</div>{!message&&!trips.length&&<p className="p-6 text-sm text-slate-500">No booking requests yet.</p>}</section>;
}
