-- Administrator qualification; isolated fixtures and all writes roll back.
DO $$ DECLARE t uuid:=gen_random_uuid();p uuid:=gen_random_uuid();rt uuid:=gen_random_uuid();rp uuid:=gen_random_uuid();u uuid;d date:=(clock_timestamp() AT TIME ZONE 'America/Chicago')::date+1;r jsonb;report text;
BEGIN BEGIN
 SELECT user_id INTO STRICT u FROM irp_pms.memberships WHERE tenant_id='faa76112-c793-43db-92bd-f9faecd8d93a' AND role='owner' LIMIT 1;
 INSERT INTO irp_pms.tenants(id,name) VALUES(t,'Temporary revenue preflight qualification');
 INSERT INTO irp_pms.properties(tenant_id,id,name,currency) VALUES(t,p,'Temporary pricing facts property','USD');
 INSERT INTO irp_pms.memberships(tenant_id,user_id,role) VALUES(t,u,'owner');
 INSERT INTO irp_pms.room_types(tenant_id,property_id,id,name) VALUES(t,p,rt,'Temporary room type');
 INSERT INTO irp_pms.rooms(tenant_id,property_id,room_type_id,label,housekeeping) VALUES(t,p,rt,'T1','Clean'),(t,p,rt,'T2','Clean');
 INSERT INTO irp_pms.rate_plans(tenant_id,property_id,id,room_type_id,name,tax_basis_points,active) VALUES(t,p,rp,rt,'Temporary plan',0,true);
 INSERT INTO irp_pms.nightly_capacity(tenant_id,property_id,room_type_id,stay_date,units) VALUES(t,p,rt,d,2);
 INSERT INTO irp_pms.nightly_rates(tenant_id,property_id,plan_id,stay_date,amount_minor) VALUES(t,p,rp,d,10000);
 PERFORM set_config('request.jwt.claim.sub',u::text,true);
 r:=public.irp_pms_pilot_revenue_facts_preflight(t,p,rp,1,d,10000,2,0);
 IF r->>'facts_match'<>'true' OR r->>'write_authorized'<>'false' OR r->'changed_fields'<>'[]'::jsonb THEN RAISE EXCEPTION 'Matching facts failed';END IF;
 UPDATE irp_pms.nightly_rates SET amount_minor=11000 WHERE tenant_id=t;
 r:=public.irp_pms_pilot_revenue_facts_preflight(t,p,rp,1,d,10000,2,0);
 IF r->'changed_fields'<>'["current_rate_minor"]'::jsonb THEN RAISE EXCEPTION 'Price drift missed';END IF;
 UPDATE irp_pms.nightly_rates SET amount_minor=10000 WHERE tenant_id=t;
 UPDATE irp_pms.nightly_capacity SET units=1 WHERE tenant_id=t;
 r:=public.irp_pms_pilot_revenue_facts_preflight(t,p,rp,1,d,10000,2,0);
 IF r->'changed_fields'<>'["effective_units"]'::jsonb THEN RAISE EXCEPTION 'Capacity drift missed';END IF;
 UPDATE irp_pms.nightly_capacity SET units=2 WHERE tenant_id=t;
 INSERT INTO irp_pms.reservations(tenant_id,property_id,source,source_booking_id,source_version,payload_hash,status,room_type_id,arrival,departure,guests,accommodation_minor,taxes_minor,ota_fees_minor,guest_total_minor)
 VALUES(t,p,'direct','temporary-facts',1,repeat('a',64),'Confirmed',rt,d,d+1,1,10000,0,0,10000);
 r:=public.irp_pms_pilot_revenue_facts_preflight(t,p,rp,1,d,10000,2,0);
 IF r->'changed_fields'<>'["reserved_units"]'::jsonb THEN RAISE EXCEPTION 'Booking drift missed';END IF;
 UPDATE irp_pms.reservations SET status='Cancelled' WHERE tenant_id=t;
 r:=public.irp_pms_pilot_revenue_facts_preflight(t,p,rp,1,d,10000,2,0);
 IF r->>'facts_match'<>'true' THEN RAISE EXCEPTION 'Cancellation not reflected';END IF;
 UPDATE irp_pms.rate_plans SET version=2,active=false WHERE tenant_id=t;
 r:=public.irp_pms_pilot_revenue_facts_preflight(t,p,rp,1,d,10000,2,0);
 IF r->'changed_fields'<>'["plan_version","active"]'::jsonb THEN RAISE EXCEPTION 'Plan drift missed';END IF;
 UPDATE irp_pms.rate_plans SET version=1,active=true WHERE tenant_id=t;
 DELETE FROM irp_pms.nightly_capacity WHERE tenant_id=t;
 DELETE FROM irp_pms.nightly_rates WHERE tenant_id=t;
 r:=public.irp_pms_pilot_revenue_facts_preflight(t,p,rp,1,d,10000,2,0);
 IF r->'changed_fields'<>'["current_rate_minor","effective_units"]'::jsonb THEN RAISE EXCEPTION 'Missing facts accepted';END IF;
 BEGIN PERFORM public.irp_pms_pilot_revenue_facts_preflight(t,p,rp,1,d,NULL,2,0);RAISE EXCEPTION 'Null evidence accepted';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 BEGIN PERFORM public.irp_pms_pilot_revenue_facts_preflight(t,p,rp,1,d-2,10000,2,0);RAISE EXCEPTION 'Past night accepted';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 BEGIN PERFORM public.irp_pms_pilot_revenue_facts_preflight(t,p,gen_random_uuid(),1,d,10000,2,0);RAISE EXCEPTION 'Unknown plan accepted';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 UPDATE irp_pms.memberships SET role='staff' WHERE tenant_id=t;
 BEGIN PERFORM public.irp_pms_pilot_revenue_facts_preflight(t,p,rp,1,d,10000,2,0);RAISE EXCEPTION 'Staff accepted';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 IF EXISTS(SELECT 1 FROM irp_pms.rate_actions WHERE tenant_id=t) THEN RAISE EXCEPTION 'Preflight wrote a rate action';END IF;
 RAISE SQLSTATE 'ZX001' USING DETAIL='{"matching_facts":"passed","price_drift":"detected","capacity_drift":"detected","booking_drift":"detected","cancellation":"reflected","plan_drift":"detected","missing_facts":"detected","null_input":"denied","past_night":"denied","unknown_plan":"denied","staff":"denied","rate_actions":0}';
 EXCEPTION WHEN SQLSTATE 'ZX001' THEN GET STACKED DIAGNOSTICS report=PG_EXCEPTION_DETAIL;END;
 PERFORM set_config('irp_test.preflight_result',report,true);
END $$;
SELECT current_setting('irp_test.preflight_result')::jsonb AS result;
