import type { PmsProviderId, PmsProviderManifest } from "./types";

const fullReservationCapabilities = [
  "availability",
  "rates",
  "inventory",
  "reservations",
  "cancellations",
  "webhooks",
] as const;

const standardConfiguration = ["BASE_URL", "CLIENT_ID", "CLIENT_SECRET"] as const;

export const pmsProviders: readonly PmsProviderManifest[] = [
  {
    id: "oracle-opera",
    name: "Oracle OPERA / OPERA Cloud",
    vendor: "Oracle Hospitality",
    accessModel: "public_partner_platform",
    capabilities: fullReservationCapabilities,
    certificationRequired: true,
    environmentPrefix: "PMS_ORACLE_OPERA",
    requiredConfiguration: [...standardConfiguration, "APP_KEY", "HOTEL_ID"],
    documentationUrl: "https://docs.oracle.com/en/industries/hospitality/integration-platform/",
    notes: "Use Oracle Hospitality Integration Platform (OHIP) credentials issued for each approved environment and hotel chain/property scope.",
  },
  {
    id: "hilton-pep",
    name: "Hilton PEP",
    vendor: "Hilton",
    accessModel: "brand_certification",
    capabilities: fullReservationCapabilities,
    certificationRequired: true,
    environmentPrefix: "PMS_HILTON_PEP",
    requiredConfiguration: ["BASE_URL", "API_CREDENTIAL", "VALIDATION_PATH"],
    documentationUrl: "https://stories.hilton.com/releases/hotel-key-partnership",
    notes: "Connectivity is brand-controlled. Activate only after Hilton approves the integration and supplies endpoint, property, and credential details.",
  },
  {
    id: "hilton-onq",
    name: "Hilton OnQ",
    vendor: "Hilton",
    accessModel: "brand_certification",
    capabilities: fullReservationCapabilities,
    certificationRequired: true,
    environmentPrefix: "PMS_HILTON_ONQ",
    requiredConfiguration: ["BASE_URL", "API_CREDENTIAL", "VALIDATION_PATH"],
    documentationUrl: "https://pim.hilton.com/HiltonWebPim/Help/Facility_Details/facility_details_screen.htm",
    notes: "Legacy OnQ connectivity is property- and brand-controlled and may require a Hilton-approved connectivity intermediary.",
  },
  {
    id: "marriott-fosse",
    name: "FOSSE",
    vendor: "Marriott International",
    accessModel: "brand_certification",
    capabilities: fullReservationCapabilities,
    certificationRequired: true,
    environmentPrefix: "PMS_MARRIOTT_FOSSE",
    requiredConfiguration: ["BASE_URL", "API_CREDENTIAL", "VALIDATION_PATH"],
    documentationUrl: "https://www.hotel-development.marriott.com/resourcefiles/fdd-document/2024-ri-fdd-3-31-2024.pdf",
    notes: "FOSSE connectivity requires Marriott approval and an issued integration specification or certified connectivity partner.",
  },
  {
    id: "marriott-fs-pms",
    name: "FS-PMS",
    vendor: "Marriott International",
    accessModel: "brand_certification",
    capabilities: fullReservationCapabilities,
    certificationRequired: true,
    environmentPrefix: "PMS_MARRIOTT_FS_PMS",
    requiredConfiguration: ["BASE_URL", "API_CREDENTIAL", "VALIDATION_PATH"],
    documentationUrl: "https://ofhub.marriott.com/wp-content/uploads/2015/03/Open-Questions-on-POS-031515.pdf",
    notes: "FS-PMS connectivity requires Marriott approval and property-level authorization before reservation traffic is enabled.",
  },
  {
    id: "hotelkey",
    name: "HotelKey",
    vendor: "HotelKey",
    accessModel: "vendor_partnership",
    capabilities: fullReservationCapabilities,
    certificationRequired: true,
    environmentPrefix: "PMS_HOTELKEY",
    requiredConfiguration: ["BASE_URL", "API_CREDENTIAL", "VALIDATION_PATH"],
    documentationUrl: "https://www.hotelkeyapp.com/system-integrations",
    notes: "Activate after HotelKey approves the partnership and supplies production API documentation, credentials, and property mappings.",
  },
  {
    id: "oracle-opera-5", name: "Oracle OPERA 5", vendor: "Oracle Hospitality",
    accessModel: "vendor_partnership", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_ORACLE_OPERA_5",
    requiredConfiguration: standardConfiguration,
    documentationUrl: "https://docs.oracle.com/cd/E98457_01/opera_5_6_core_help/20460.htm",
    notes: "Legacy OPERA 5 connectivity must use an Oracle-approved interface and property-authorized endpoint.",
  },
  {
    id: "infor-hms", name: "Infor HMS", vendor: "Infor",
    accessModel: "vendor_partnership", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_INFOR_HMS",
    requiredConfiguration: standardConfiguration,
    documentationUrl: "https://docs.infor.com/inforos/2026.x/en-us/useradminlib_cloud/apigatewayag_cloud/wps1514559141744.html",
    notes: "Activate after Infor or an authorized hotel partner supplies API access and property mappings.",
  },
  {
    id: "agilysys-pms", name: "Agilysys PMS", vendor: "Agilysys",
    accessModel: "vendor_partnership", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_AGILYSYS",
    requiredConfiguration: standardConfiguration,
    documentationUrl: "https://www.agilysys.com/en/products/pms/",
    notes: "Requires an approved Agilysys integration path and property authorization.",
  },
  {
    id: "planet-protel", name: "Planet Protel", vendor: "Planet",
    accessModel: "vendor_partnership", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_PLANET_PROTEL",
    requiredConfiguration: standardConfiguration,
    documentationUrl: "https://www.weareplanet.com/hotel-pms",
    notes: "Activate only with Planet-issued credentials, endpoint details, and hotel scope.",
  },
  {
    id: "mews", name: "Mews", vendor: "Mews",
    accessModel: "public_partner_platform", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_MEWS",
    requiredConfiguration: ["BASE_URL", "CLIENT_TOKEN", "ACCESS_TOKEN", "CLIENT"],
    documentationUrl: "https://mews-systems.gitbook.io/connector-api/",
    notes: "Use Mews-approved connector credentials and validate each property mapping before live traffic.",
  },
  {
    id: "stayntouch", name: "Stayntouch", vendor: "Stayntouch",
    accessModel: "vendor_partnership", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_STAYNTOUCH",
    requiredConfiguration: ["BASE_URL", "ACCESS_TOKEN"],
    documentationUrl: "https://api-specs.stayntouch.com/v2/index.html",
    notes: "Requires Stayntouch partner access and hotel authorization.",
  },
  {
    id: "cloudbeds", name: "Cloudbeds", vendor: "Cloudbeds",
    accessModel: "public_partner_platform", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_CLOUDBEDS",
    requiredConfiguration: ["BASE_URL", "API_KEY"],
    documentationUrl: "https://developers.cloudbeds.com/",
    notes: "Use approved Cloudbeds API credentials and property-scoped authorization.",
  },
  {
    id: "sihot", name: "SIHOT", vendor: "GUBSE",
    accessModel: "vendor_partnership", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_SIHOT",
    requiredConfiguration: ["BASE_URL", "USER", "PASSWORD", "HOTEL", "PRODUCT_ID"],
    documentationUrl: "https://partner.sihot.com/SIHOTAPI/",
    notes: "Requires SIHOT-approved interface access and property-specific mappings.",
  },
  {
    id: "rms-cloud", name: "RMS Cloud", vendor: "RMS Cloud",
    accessModel: "vendor_partnership", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_RMS_CLOUD",
    requiredConfiguration: ["BASE_URL", "AGENT_ID", "AGENT_PASSWORD", "CLIENT_ID", "CLIENT_PASSWORD", "PROPERTY_ID"],
    documentationUrl: "https://www.rmscloud.com/platform/api",
    notes: "Activate after RMS Cloud approves API access and property scope.",
  },
  {
    id: "maestro-pms", name: "Maestro PMS", vendor: "Maestro",
    accessModel: "vendor_partnership", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_MAESTRO",
    requiredConfiguration: ["BASE_URL", "ACCESS_TOKEN", "VALIDATION_PATH"],
    documentationUrl: "https://www.maestropms.com/interfaces-open-apis-integration-pms-partners.html",
    notes: "Requires a Maestro-approved integration and hotel authorization.",
  },
  {
    id: "apaleo", name: "Apaleo", vendor: "Apaleo",
    accessModel: "public_partner_platform", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_APALEO",
    requiredConfiguration: standardConfiguration,
    documentationUrl: "https://apaleo.dev/",
    notes: "Use an approved OAuth application and validate hotel resource mappings before activation.",
  },
  {
    id: "shiji-pms", name: "Shiji PMS", vendor: "Shiji Group",
    accessModel: "vendor_partnership", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_SHIJI",
    requiredConfiguration: ["BASE_URL", "ACCESS_TOKEN", "VALIDATION_PATH"],
    documentationUrl: "https://www.shijigroup.com/shiji-platform",
    notes: "Requires Shiji partner approval, credentials, and property-level authorization.",
  },
  {
    id: "guestline", name: "Guestline", vendor: "Guestline",
    accessModel: "vendor_partnership", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_GUESTLINE",
    requiredConfiguration: standardConfiguration,
    documentationUrl: "https://developers.guestline.com/",
    notes: "Activate after Guestline supplies approved connectivity and property mappings.",
  },
  {
    id: "ezee-absolute", name: "eZee Absolute", vendor: "Yanolja Cloud Solution",
    accessModel: "vendor_partnership", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_EZEE_ABSOLUTE",
    requiredConfiguration: standardConfiguration,
    documentationUrl: "https://www.yanoljacloudsolution.com/",
    notes: "Requires authorized eZee connectivity credentials and hotel scope.",
  },
  {
    id: "clock-pms-plus", name: "Clock PMS+", vendor: "Clock Software",
    accessModel: "vendor_partnership", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_CLOCK_PMS_PLUS",
    requiredConfiguration: standardConfiguration,
    documentationUrl: "https://api-docs.clock-software.com/",
    notes: "Activate after Clock Software approves the integration and property access.",
  },
  {
    id: "hotelogix", name: "Hotelogix", vendor: "Hotelogix",
    accessModel: "vendor_partnership", capabilities: fullReservationCapabilities,
    certificationRequired: true, environmentPrefix: "PMS_HOTELOGIX",
    requiredConfiguration: standardConfiguration,
    documentationUrl: "https://www.hotelogix.com/other-interfaces",
    notes: "Requires Hotelogix-approved API access and property mappings.",
  },
] as const;

export function getPmsProvider(providerId: PmsProviderId) {
  return pmsProviders.find((provider) => provider.id === providerId);
}

